export enum ErrorCode {
  // User
  USER_NOT_FOUND = 'U001',
  USER_INVALID_PASSWORD = 'U002',
  USER_NICKNAME_DUPLICATED = 'U003',
  USER_EMAIL_DUPLICATED = 'U004',
  USER_LOGIN_REQUIRED = 'U005',

  // Board
  BOARD_NOT_FOUND = 'B001',
  CONTENT_NULL = 'B003',
  INVALID_POST_DELETE = 'B005',
  NODE_ALREADY_WRITTEN = 'B004',
  NODE_NOT_FOUND = 'N001',
  TITLE_NULL = 'B002',

  // Comment
  COMMENT_NOT_FOUND = 'C001',
  COMMENT_PERMISSION_DENIED = 'C002',
}
