
export enum ErrorCode {
    BOARD_NOT_FOUND = 'BOARD_NOT_FOUND',
    CONTENT_NULL = 'CONTENT_NULL',
    INVALID_POST_DELETE = 'INVALID_POST_DELETE',
    NODE_ALREADY_WRITTEN = 'NODE_ALREADY_WRITTEN',
    NODE_NOT_FOUND = 'NODE_NOT_FOUND',
    TITLE_NULL = 'TITLE_NULL',
}
